<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" {...$$props}
	><circle cx="12" cy="12" r="0" fill="currentColor"
		><animate
			id="svgSpinnersPulse40"
			fill="freeze"
			attributeName="r"
			begin="0;svgSpinnersPulse42.begin+0.6s"
			calcMode="spline"
			dur="1.2s"
			keySplines=".52,.6,.25,.99"
			values="0;11"
		/><animate
			fill="freeze"
			attributeName="opacity"
			begin="0;svgSpinnersPulse42.begin+0.6s"
			calcMode="spline"
			dur="1.2s"
			keySplines=".52,.6,.25,.99"
			values="1;0"
		/></circle
	><circle cx="12" cy="12" r="0" fill="currentColor"
		><animate
			id="svgSpinnersPulse41"
			fill="freeze"
			attributeName="r"
			begin="svgSpinnersPulse40.begin+0.6s"
			calcMode="spline"
			dur="1.2s"
			keySplines=".52,.6,.25,.99"
			values="0;11"
		/><animate
			fill="freeze"
			attributeName="opacity"
			begin="svgSpinnersPulse40.begin+0.6s"
			calcMode="spline"
			dur="1.2s"
			keySplines=".52,.6,.25,.99"
			values="1;0"
		/></circle
	><circle cx="12" cy="12" r="0" fill="currentColor"
		><animate
			id="svgSpinnersPulse42"
			fill="freeze"
			attributeName="r"
			begin="svgSpinnersPulse40.begin+0.8s"
			calcMode="spline"
			dur="1.2s"
			keySplines=".52,.6,.25,.99"
			values="0;11"
		/><animate
			fill="freeze"
			attributeName="opacity"
			begin="svgSpinnersPulse40.begin+0.8s"
			calcMode="spline"
			dur="1.2s"
			keySplines=".52,.6,.25,.99"
			values="1;0"
		/></circle
	></svg
>
